Update Tumblr and SmugMug OSINT Templates with Improved Username Validation
projectdiscovery/nuclei-templates pull request #10990
Opened 2024-10-10 21:05 UTC by MillerMedia

### Template / PR Information

• Added templates to detect user profile information for Tumblr and SmugMug using OSINT techniques.

• The templates validate usernames and avoid false positives for cases where periods (.) are incorrectly interpreted as subdomain separators.

• References: N/A

### Template Validation

I've validated this template locally?
- [ x] YES
- [ ] NO

#### Additional Details (leave it blank if not applicable)

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

2024-10-11 10:43 UTC, GeorginaReeder commented
Thanks so much for your contribution @MillerMedia ! :)

2024-11-03 19:48 UTC, princechaddha commented
Hello @MillerMedia, The response time to this PR was much longer than usual. Thank you for taking the time to update this template and for contributing to this project 🍻

I’ve made some changes, yet the replace helper still isn’t working as expected. I am checking in with the team to confirm this.

You can also join our [discord server](https://discord.com/invite/projectdiscovery). It's a great place to connect with fellow contributors and stay updated with the latest developments. Thank you once again

2024-11-04 05:24 UTC, dwisiswant0 requested changes
when declaring a DSL expr, the functions inside don't need to be wrapped in tags - and it's unnecessary since the var can be used directly.

2024-11-04 05:24 UTC, dwisiswant0 commented on http/osint/user-enumeration/smugmug.yaml
> +  valid_username: "{{replace('{{user}}', '.', '')}}"
```suggestion
  valid_username: "{{replace(user, '.', '')}}"
```

2024-11-04 05:24 UTC, dwisiswant0 commented on http/osint/user-enumeration/tumblr.yaml
> +  valid_username: "{{replace('{{user}}', '.', '')}}"
```suggestion
  valid_username: "{{replace(user, '.', '')}}"
```

2024-11-04 06:40 UTC, dwisiswant0 approved these changes

2024-11-04 13:15 UTC, princechaddha approved these changes

2024-11-04 13:15 UTC, merged

2024-11-04 21:26 UTC, MillerMedia commented
Thanks for the clarity on this! Glad to see it was approved; thank you!