Add CVE-2020-35489 Detection
projectdiscovery/nuclei-templates pull request #1124
Opened 2021-03-21 18:09 UTC by alanbriangh

CVE-2020-35489 Detection

2021-03-21 19:53 UTC, ehsandeep commented
thanks for sharing this template @alanbriangh, we will see if we can update the template with file upload POC instead of version check.

2021-03-22 09:17 UTC, nrathaus requested changes
description: The contact-form-7 (aka Contact Form 7) plugin before 5.3.2 for WordPress allows Unrestricted File Upload and remote code execution because a filename may contain special characters.

reference: |
  - https://contactform7.com/2020/12/17/contact-form-7-532/
  - https://wpscan.com/vulnerability/10508
  - https://www.getastra.com/blog/911/plugin-exploit/contact-form-7-unrestricted-file-upload/
  - https://www.jinsonvarghese.com/unrestricted-file-upload-in-contact-form-7/

Detection via regex:
([0-4]\.|5\.[0-2]\.|5\.3\.[0-1])

2021-03-22 13:33 UTC, alanbriangh commented
Hi @nrathaus I tested the regex on https://regex101.com and I think not work well with these combinations (for example):

5.1.9
5.1.1
2.4.3

Could you check? thanks!

2021-03-22 13:57 UTC, geeknik commented
This might work: `^((?!5.3.2)[\s\S])*$`. Unfortunately, it will match on stuff above 5.3.2 as well as below but I think we're at the limit of what regex can do here.

2021-03-22 14:32 UTC, nrathaus commented
Not sure what you mean by doesn't work, we don't need a complete match here, a partial match of the version would also work, if you need a complete match use this:
`^(([0-4]\.[0-9]+\.[0-9]+)|(5\.[0-2]\.[0-9]+)|(5\.3\.[0-1]$))`

2021-03-23 13:51 UTC, alanbriangh commented
You're right @nrathaus. It was my mistake. Thank you!

2021-03-24 19:59 UTC, ehsandeep commented
Thank you @alanbriangh for creating a template for this.

2021-03-24 19:59 UTC, merged