Create CVE-2019-4781.yaml
projectdiscovery/nuclei-templates pull request #1734
Opened 2021-06-19 20:18 UTC by darrenmartyn

Need some feedback on this, tested it out and it works just fine.

2021-06-19 20:39 UTC, darrenmartyn commented
It is actually CVE-2019-7481, I just keep making a damn typo.

2021-06-19 20:51 UTC, geeknik requested changes
Line 4 has trailing spaces that need to be removed.

Consider adding `sonicwall` and `sqli` to the tags.

Line 16 shows `/cgi-bin/supportInstaller`, I thought the endpoint was `/cgi-bin/supportLogin` in relation to the `customerTID` SQL injection? Please confirm. 

It is possible the single matcher is not enough, if possible, considering adding another.

2021-06-19 21:45 UTC, darrenmartyn commented
Fixed the trailing spaces (I think) and added the suggested tags. 

The SQLi is in the supportInstaller endpoint, see the below gist for the PoC from CrowdStrike: https://gist.github.com/darrenmartyn/eb06e5fbc2b005a4de78ddc594bccaa7

2021-06-19 21:59 UTC, geeknik commented
LGTM 👍🏻

2021-06-22 07:50 UTC, princechaddha commented
Thanks for sharing this template @darrenmartyn 🔥

2021-06-22 07:51 UTC, merged