17 New Templates Added
projectdiscovery/nuclei-templates pull request #2125
Opened 2021-07-21 08:40 UTC by DhiyaneshGeek

2021-07-21 17:46 UTC, toufik-airane commented
Impressive work! Definitely will look at these templates ASAP.

2021-07-21 17:55 UTC, geeknik commented on exposures/configs/git-credentials-disclosure.yaml
> +id: git-credentials-disclosure
We added a [similar template](https://github.com/geeknik/the-nuclei-templates/blob/main/git-credentials.yaml) to our public repo a couple of months ago, zero false positives thus far.

```
id: git-credentials
info:
  name: Detect .git-credentials
  author: geeknik
  description: Github Authentication
  severity: high
  tags: github,auth

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.git-credentials"

    matchers-condition: and
    matchers:
      - type: word
        part: header
        words:
          - "text/plain"
      - type: word
        words:
          - "https://"
          - "@github.com"
      - type: status
        status:
          - 200
```

2021-07-21 17:57 UTC, geeknik commented
Nice. Almost half of those are from our public and private Git repo. 🤣

2021-07-22 17:00 UTC, toufik-airane commented on exposures/configs/appsec-yml-disclosure.yaml
> +          - "files:"
```suggestion
          - "version"
          - "os"
          - "files"
```

2021-07-22 17:01 UTC, toufik-airane commented on exposures/configs/appsec-yml-disclosure.yaml
> +          - "files:"
It seems the matcher doesn't include semi-colon :. So should it just be `"\"version\""`, `"\"os\""` and `"\"files\""`?
https://github.com/detectify/ugly-duckling/blob/master/modules/crowdsourced/appsec-yml-disclosure.json#L25

2021-07-22 17:01 UTC, toufik-airane commented on exposures/configs/appsec-yml-disclosure.yaml
> +          - "source:"
```suggestion
```

2021-07-22 17:01 UTC, toufik-airane commented on exposures/configs/appsec-yml-disclosure.yaml
> +          - "source:"
I don't see a `"source"` word in
https://github.com/detectify/ugly-duckling/blob/master/modules/crowdsourced/appsec-yml-disclosure.json.

2021-07-22 17:02 UTC, toufik-airane commented on exposures/configs/appsec-yml-disclosure.yaml
> +
We should check the header.

2021-07-22 17:03 UTC, toufik-airane commented on exposures/configs/github-workflows-disclosure.yaml
> +    matchers-condition: and
```suggestion
      - "{{BaseURL}}/.github/workflows/docker.yml"

    matchers-condition: and
```

2021-07-22 17:03 UTC, toufik-airane commented on exposures/configs/github-workflows-disclosure.yaml
> +    matchers-condition: and
Add a space.

2021-07-22 17:04 UTC, toufik-airane commented on exposures/configs/github-workflows-disclosure.yaml
> +          - "Content-Type: text/html"
```suggestion
          - "Content-Type: application/yaml"
```

2021-07-22 17:04 UTC, toufik-airane commented on exposures/configs/github-workflows-disclosure.yaml
> +          - "Content-Type: text/html"
https://github.com/detectify/ugly-duckling/blob/master/modules/crowdsourced/github-workflows-disclosure.json#L39

2021-07-22 17:06 UTC, toufik-airane commented on exposures/configs/github-workflows-disclosure.yaml
> +      - type: word
```suggestion
        part: body
        condition: and

      - type: word
```

2021-07-22 17:06 UTC, toufik-airane commented on exposures/configs/github-workflows-disclosure.yaml
> +      - type: status
```suggestion
        part: header

      - type: status
```

2021-07-22 17:06 UTC, toufik-airane commented on exposures/configs/github-workflows-disclosure.yaml
> +      - type: status
more space :)

2021-07-22 17:08 UTC, toufik-airane commented on exposures/configs/hp-ilo-serial-key-disclosure.yaml
> +      - type: word
```suggestion
        part: body
        condition: and

      - type: word
```

2021-07-22 17:09 UTC, toufik-airane commented on exposures/configs/hp-ilo-serial-key-disclosure.yaml
> +    matchers-condition: and
```suggestion
      - "{{BaseURL}}/xmldata?item=CpqKey"

    matchers-condition: and
```

2021-07-22 17:09 UTC, toufik-airane commented on exposures/configs/hp-ilo-serial-key-disclosure.yaml
> +      - type: status
```suggestion
        part: header

      - type: status
```

2021-07-22 17:10 UTC, toufik-airane commented on exposures/configs/kubernetes-kustomization-disclosure.yaml
> +    matchers-condition: and
```suggestion
      - "{{BaseURL}}/kustomization.yml"

    matchers-condition: and
```

2021-07-22 17:11 UTC, toufik-airane commented on exposures/configs/kubernetes-kustomization-disclosure.yaml
> +      - type: word
```suggestion
        part: body

      - type: word
```

2021-07-22 17:11 UTC, toufik-airane commented on exposures/configs/kubernetes-kustomization-disclosure.yaml
> +      - type: status
```suggestion
        part: header

      - type: status
```

2021-07-22 17:12 UTC, toufik-airane commented on exposures/files/php-user-ini-disclosure.yaml
> +    matchers-condition: and
```suggestion
      - "{{BaseURL}}/.user.ini"

    matchers-condition: and
```

2021-07-22 17:12 UTC, toufik-airane commented on exposures/files/php-user-ini-disclosure.yaml
> +      - type: status
```suggestion
        part: body
      - type: status
```

2021-07-22 17:34 UTC, toufik-airane requested changes
Very very very good work! 🔥🔥🔥
I've made some comments and feedback.

Note for the future, by default the `condition` and `matchers-condition` are set to `or`.

Again thank you very much @DhiyaneshGeek for this awesome work. 🚀
And thanks to the https://github.com/detectify/ugly-duckling/ project for the inspiration.

2021-07-22 17:34 UTC, toufik-airane commented on exposures/files/php-user-ini-disclosure.yaml
> +      - type: status
```suggestion
        part: body
        condition: and

      - type: status
```

2021-07-22 17:34 UTC, toufik-airane commented on exposures/files/putty-private-key-disclosure.yaml
> +    matchers-condition: and
```suggestion
      - "{{BaseURL}}/my.ppk"

    matchers-condition: and
```

2021-07-22 17:34 UTC, toufik-airane commented on exposures/files/putty-private-key-disclosure.yaml
> +      - type: status
```suggestion
        part: body
        condition: and

      - type: status
```

2021-07-22 17:34 UTC, toufik-airane commented on exposures/files/pyproject-disclosure.yaml
> +    matchers-condition: and
```suggestion
      - "{{BaseURL}}/pyproject.toml"

    matchers-condition: and
```

2021-07-22 17:34 UTC, toufik-airane commented on exposures/files/pyproject-disclosure.yaml
> +      - type: status
```suggestion
        part: body
        condition: and

      - type: status
```

2021-07-22 17:34 UTC, toufik-airane commented on vulnerabilities/other/nginx-merge-slashes-path-traversal.yaml
> +      - "{{BaseURL}}//////../../../etc/passwd"
```suggestion
      - "{{BaseURL}}///////../../../etc/passwd"
```

2021-07-22 17:34 UTC, toufik-airane commented on vulnerabilities/other/nginx-merge-slashes-path-traversal.yaml
> +    matchers-condition: and
```suggestion
      - "{{BaseURL}}///../app.js"

    matchers-condition: and
```

2021-07-22 17:34 UTC, toufik-airane commented on vulnerabilities/other/nginx-merge-slashes-path-traversal.yaml
> +      - type: status
```suggestion
        part: body
        condition: or

      - type: status
```

2021-07-22 17:34 UTC, toufik-airane commented on misconfiguration/clockwork-dashboard-exposure.yaml
> +    matchers-condition: and
```suggestion
      - "{{BaseURL}}/__clockwork/latest"

    matchers-condition: and
```

2021-07-22 17:34 UTC, toufik-airane commented on misconfiguration/clockwork-dashboard-exposure.yaml
> +      - type: word
```suggestion
        condition: and

      - type: word
```

2021-07-22 17:34 UTC, toufik-airane commented on exposures/files/ruby-on-rails-secret-token-disclosure.yaml
> +      - type: status
```suggestion
        part: body
        condition: and

      - type: status
```

2021-07-22 17:34 UTC, toufik-airane commented on exposures/files/snyk-ignore-file-disclosure.yaml
> +    matchers-condition: and
```suggestion
      - "{{BaseURL}}/.snyk"

    matchers-condition: and
```

2021-07-22 17:34 UTC, toufik-airane commented on exposures/files/snyk-ignore-file-disclosure.yaml
> +          - '# Snyk (https://snyk.io) policy file, patches or ignores known vulnerabilities.'
```suggestion
          - "# Snyk (https://snyk.io) policy file, patches or ignores known vulnerabilities."
```

2021-07-22 17:34 UTC, toufik-airane commented on exposures/files/snyk-ignore-file-disclosure.yaml
> +      - type: status
```suggestion
        part: body

      - type: status
```

2021-07-22 17:34 UTC, toufik-airane commented on exposures/files/thumbs-db-disclosure.yaml
> +      - type: status
```suggestion
      - type: binary
        binary:
          - 'D0CF11E0A1B11AE1'
        part: body

      - type: status
```

2021-07-22 17:34 UTC, toufik-airane commented on exposures/files/thumbs-db-disclosure.yaml
> +      - type: status
Have to test it on run-time.

2021-07-22 17:34 UTC, toufik-airane commented on exposures/logs/roundcube-log-disclosure.yaml
> +    matchers-condition: and
```suggestion
      - "{{BaseURL}}/roundcube/logs/errors.log"

    matchers-condition: and
```

2021-07-22 17:34 UTC, toufik-airane commented on exposures/logs/roundcube-log-disclosure.yaml
> +      - type: status
```suggestion
        part: body

      - type: status
```

2021-07-22 17:34 UTC, toufik-airane commented on exposures/logs/roundcube-log-disclosure.yaml
> +      - type: status
more spaces 🤤

2021-07-23 06:07 UTC, DhiyaneshGeek commented
@toufik-airane after accepting the suggestion the YAML validation failed

2021-07-23 06:22 UTC, dhayalandeena10 commented
help

2021-07-23 06:23 UTC, dhayalandeena10 commented
made

2021-07-23 06:24 UTC, dhayalandeena10 commented
new


On Fri, Jul 23, 2021 at 11:53 AM Deena Dhayalan ***@***.***>
wrote:

> made
>

2021-07-23 06:28 UTC, dhayalandeena10 commented
2002

-- 
This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

2021-07-23 06:34 UTC, dhayalandeena10 commented
new

2021-07-23 06:35 UTC, dhayalandeena10 commented
new

2021-07-23 12:20 UTC, DhiyaneshGeek commented on exposures/configs/dockerfile-hidden-disclosure.yaml
> +          - '^(?:FROM(?:CACHE)?|RUN|ADD|WORKDIR|ENV|EXPOSE|\\#)\\s+[ -~]+'
@ehsandeep regex updated 
![image](https://user-images.githubusercontent.com/24750220/126780745-1cfc73b5-c133-4310-8fb5-f714a15a3646.png)

2021-07-23 19:01 UTC, ehsandeep commented on exposures/configs/git-credentials-disclosure.yaml
> +      - type: word
Yes, it does by adding `negative: true` to any matcher, updated the template accordingly.

```yaml
      - type: word
        part: header
        words:
          - "text/html"
        negative: true
```

2021-07-23 21:48 UTC, ehsandeep approved these changes

2021-07-23 21:56 UTC, merged