Create mantis-detect.yaml
projectdiscovery/nuclei-templates pull request #2149
Opened 2021-07-22 13:49 UTC by MaKyOtOx

### Template / PR Information

Mantis Bug Tracker portal detection
- References: https://www.mantisbt.org/

### Template Validation

I've validated this template locally?
- [X] YES
- [ ] NO

#### Additional Details (leave it blank if not applicable)

### Additional References:
- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/.github/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

2021-07-22 15:49 UTC, geeknik commented
Hello, thank you for the submission. A check for MantisBT currently exists in the `tech-detect.yaml` template here: 

https://github.com/projectdiscovery/nuclei-templates/blob/3b400caab08676cedbefe117ecbed8f8f302e61d/technologies/tech-detect.yaml#L1843

2021-07-22 17:48 UTC, toufik-airane requested changes
Dear @MaKyOtOx, thank you for your contribution.

@geeknik I won't be shocked to see another Tech detection in the _exposed-panels_ folder, what do you think?

2021-07-22 17:48 UTC, toufik-airane commented on exposed-panels/mantis-detect.yaml
> +    matchers:
```suggestion
      - "{{BaseURL}}/login_page.php"

    matchers:
```

2021-07-22 18:24 UTC, geeknik commented
> @geeknik I won't be shocked to see another Tech detection in the _exposed-panels_ folder, what do you think?

I'm all for new templates! 👍🏻

2021-07-23 07:27 UTC, MaKyOtOx commented
I wrote this template because the existing once did not detect my Mantis target. It's up to you to add a new template or refine the existing one

2021-07-23 20:47 UTC, ehsandeep commented
Thank you @MaKyOtOx for sharing the additional template.

2021-07-23 20:47 UTC, merged

2021-07-26 14:27 UTC, toufik-airane commented
Dear @MaKyOtOx,

Your template has been merged.

Thank you for your contribution and we hope to read you soon. :)

2021-07-26 14:32 UTC, MaKyOtOx commented
Thank Team !! More PR are coming :)