New templates added
projectdiscovery/nuclei-templates pull request #2150
Opened 2021-07-22 14:14 UTC by pussycat0x

2021-07-22 18:13 UTC, toufik-airane commented on vulnerabilities/wordpress/wp-iwp-client-listing.yaml
> +requests:
```suggestion
  tags: wordpress,listing

requests:
```

2021-07-22 18:13 UTC, toufik-airane commented on vulnerabilities/wordpress/wp-iwp-client-listing.yaml
> +    matchers-condition: and
```suggestion
      - "{{BaseURL}}/wp-content/plugins/iwp-client/"

    matchers-condition: and
```

2021-07-22 18:13 UTC, toufik-airane commented on vulnerabilities/wordpress/wp-iwp-client-listing.yaml
> +      - type: status
```suggestion
          - "wp-content/plugins/iwp-client/"

      - type: status
```

2021-07-22 18:13 UTC, toufik-airane commented on vulnerabilities/wordpress/wp-sfwd-lms-listing.yaml
> +requests:
```suggestion
  tags: wordpress,listing

requests:
```

2021-07-22 18:13 UTC, toufik-airane commented on vulnerabilities/wordpress/wp-sfwd-lms-listing.yaml
> +    matchers-condition: and
```suggestion
      - "{{BaseURL}}/wp-content/plugins/sfwd-lms/"

    matchers-condition: and
```

2021-07-22 18:13 UTC, toufik-airane commented on vulnerabilities/wordpress/wp-sfwd-lms-listing.yaml
> +      - type: status
```suggestion
          - "wp-content/plugins/sfwd-lms"
      - type: status

```

2021-07-22 18:14 UTC, toufik-airane requested changes
Dear @pussycat0x,

Thank you for your contribution.
I've made some feedback feel free to accept it.

Nice contribution. 💜

2021-07-23 18:36 UTC, ehsandeep approved these changes

2021-07-23 18:39 UTC, merged

2021-07-26 14:24 UTC, toufik-airane reviewed
LGTM 👍