Add Zimbra XSS
projectdiscovery/nuclei-templates pull request #2216
Opened 2021-07-27 07:35 UTC by pikpikcu

2021-08-02 17:40 UTC, toufik-airane requested changes
Dear @pikpikcu,

the template seems good but can we think about another matcher to avoid reflecting the matched words with the requested path?

Indeed, the word `'<svg onload=alert(document.domain)>'` can be reflected with the path `%3E%3Csvg%20onload%3Dalert%28document.domain%29%3E`.

Thank you.

2021-08-02 17:40 UTC, toufik-airane commented on cves/2018/CVE-2018-14013.yaml
> +          - '<svg onload=alert(document.domain)>'
Avoid reflecting the matched words with the requested path.

2021-08-03 07:52 UTC, merged

2021-08-03 07:53 UTC, princechaddha commented on cves/2018/CVE-2018-14013.yaml
> +          - '<svg onload=alert(document.domain)>'
hello @pikpikcu @toufik-airane, I have updated the template.

2021-08-03 13:38 UTC, toufik-airane commented on cves/2018/CVE-2018-14013.yaml
> +          - '<svg onload=alert(document.domain)>'
Thank you. @princechaddha
So could I conclude that `<script>alert()</script>` is a payload to reflect and match?