Add *description* property to nuclei-templates
projectdiscovery/nuclei-templates pull request #345
Opened 2020-08-25 20:08 UTC by toufik-airane

# Description

Recently, the update https://github.com/projectdiscovery/nuclei/pull/140 introduces a property in the nuclei template engine.
The property named **description** gives space to describe the result of a template.

However, most of the actual templates don't implement it.

# About the contribution

## Type of change

- [X] Non-breaking changes

2020-08-27 16:24 UTC, toufik-airane reviewed
@bauthard @ioribrn can we move with that first bulk?

Thanks.

2020-08-27 18:34 UTC, bauthard requested changes

2020-08-27 18:34 UTC, bauthard commented on vulnerabilities/cached-aem-pages.yaml
> +  reference: https://twitter.com/AEMSecurity
@toufik-airane `reference` field is something still needs to be added, can we comment it out for now?

2020-08-27 18:34 UTC, bauthard commented on vulnerabilities/ibm-infoprint-directory-traversal.yaml
> +  reference: https://www.exploit-db.com/exploits/47835
same as above, once we add `reference`, we can remove the #

2020-08-27 18:34 UTC, bauthard commented on vulnerabilities/microstrategy-ssrf.yaml
> +  reference: https://medium.com/@win3zz/how-i-made-31500-by-submitting-a-bug-to-facebook-d31bb046e204
This as well.

2020-08-27 18:34 UTC, bauthard commented on vulnerabilities/symfony-debugmode.yaml
> +  reference: https://github.com/synacktiv/eos
`# reference`

2020-08-27 19:38 UTC, toufik-airane commented
> @bauthard @ioribrn can we move with that first bulk?
> 
> Thanks.

Done.

2020-08-27 19:39 UTC, merged

2020-08-27 19:41 UTC, bauthard commented
Thank a lot @toufik-airane @ioribrn for adding this useful information.

2020-08-28 00:30 UTC, ioribrn commented
Thanks @bauthard