Create CNVD-2021-49104
projectdiscovery/nuclei-templates pull request #3467
Opened 2022-01-03 10:00 UTC by pikpikcu

### Template / PR Information

- Fixed CVE-2020-XXX / Added CVE-2020-XXX / Updated CVE-2020-XXX
- References:

### Template Validation

I've validated this template locally?
- [ ] YES
- [ ] NO

#### Additional Details (leave it blank if not applicable)

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/.github/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

2022-01-03 10:06 UTC, ImNightmaree requested changes
Just a few bits of advice! This should help make sure we're properly picking this up and making it so we don't expose more information than is absolutely necessary to detect the vulnerability.

2022-01-03 10:06 UTC, ImNightmaree commented on cnvd/CNVD-2021-49104.yaml
> +        <?php phpinfo();?>
Perhaps this should be replaced with {{randstr}} - we wouldn't want to leave a file which could potentially expose further weaknesses to others. This would confirm the vulnerability, and not expose further info that's unnecessary.

2022-01-03 10:06 UTC, ImNightmaree commented on cnvd/CNVD-2021-49104.yaml
> +        Content-Length: 193
These shouldn't be needed. They're autoset by Nuclei when running the template, so unless they're needed to be specific to exploit, you can remove these.

2022-01-03 10:06 UTC, ImNightmaree commented on cnvd/CNVD-2021-49104.yaml
> +          - "phpinfo()"
If you take my advice on this review - this should also be replaced with {{randstr}} so it's matched properly.

2022-01-03 10:06 UTC, ImNightmaree commented on cnvd/CNVD-2021-49104.yaml
> +  name: Pan micro E-office file upload
Capitalize please? 😄

2022-01-03 10:06 UTC, ImNightmaree commented on cnvd/CNVD-2021-49104.yaml
> +        Content-Disposition: form-data; name="Filedata"; filename="test.php"
You could also name the file {{randstr}}.php to make sure it's definitely there.

2022-01-04 06:49 UTC, princechaddha commented
@pikpikcu, thank you so much for sharing this template with the community 🙌
Please let me know if the changes look good to you cc @ImNightmaree

2022-01-04 08:11 UTC, ImNightmaree commented
All good to me @princechaddha - cheers!

2022-01-05 07:42 UTC, merged