Update credentials-disclosure.yaml
projectdiscovery/nuclei-templates pull request #347
Opened 2020-08-25 21:29 UTC by Haones

Added an additional check to also parse strings like:
`accesstoken`
`apikey`

(no `-` or `_`)

Also I didn't find in nuclei-templates docs way to pass regex flags. The problem is when there will be a string in the file like:
`ApiKey`
or
`accessToken`

It will be ignored. I had such strings in real world cases.
We need to somehow tell nuclei to use case insensitive flag of regex. Is it possible now or you'll add such an option later?

2020-08-26 05:20 UTC, Ice3man543 commented
@Haones case-insensitive matches is a very good suggestion however doing case-insensitive matches for each regex would be expensive. I'll create an issue with a strategy i have in mind.

2020-08-26 05:20 UTC, Ice3man543 requested changes

2020-08-26 05:20 UTC, Ice3man543 commented on tokens/credentials-disclosure.yaml
> +          - "zopim([_-]|)account([_-]|)key(=| =|:| :)"
I think @Haones `zopim[_-]?account[_-]?key(=| =|:| :)` is a better regex for doing the same thing since we avoid any capturing groups which take extra work out of the regex engine and simply things using a conditional `?` operator. Could you please align the PR to work this way?

2020-08-26 05:20 UTC, Ice3man543 commented on tokens/credentials-disclosure.yaml
> +          - "zopim([_-]|)account([_-]|)key(=| =|:| :)"
<img width="867" alt="Screenshot 2020-08-26 at 10 48 55 AM" src="https://user-images.githubusercontent.com/22318055/91258370-cf23ff00-e789-11ea-82a5-6a007ccbcb1a.png">
I tested with variations and it works well.

2020-08-26 05:25 UTC, Ice3man543 commented
https://github.com/projectdiscovery/nuclei/issues/261

2020-08-26 11:24 UTC, Haones commented on tokens/credentials-disclosure.yaml
> +          - "zopim([_-]|)account([_-]|)key(=| =|:| :)"
Hello @Ice3man543,

Thank you for the explanations! I added changes per your request, feel free to review them.

2020-08-27 09:34 UTC, merged

2020-08-27 09:34 UTC, bauthard commented
Thank you for updating the template @Haones