Update CVE-2018-1000129.yaml
projectdiscovery/nuclei-templates pull request #353
Opened 2020-08-27 12:27 UTC by flag007

There are two problems with this payload, / means the path, add it cannot be detected correctly, in addition, it should not be url-encoded

2020-08-28 19:14 UTC, bauthard requested changes

2020-08-28 19:14 UTC, bauthard commented on cves/CVE-2018-1000129.yaml
> +      - "{{BaseURL}}/jolokia/read<svgxxxxxx>?mimeType=text/html"
Hey, do you think we can replace this with XSS payload `<svg/onload=alert(document.domain)>` and look for a match for the same?

2020-08-30 04:33 UTC, merged

2020-08-30 04:34 UTC, bauthard commented
thanks for the update @flag007

2020-08-30 13:14 UTC, flag007 commented on cves/CVE-2018-1000129.yaml
> +      - "{{BaseURL}}/jolokia/read<svgxxxxxx>?mimeType=text/html"
No, / indicates the path and will interrupt the load

2020-08-30 13:17 UTC, bauthard commented on cves/CVE-2018-1000129.yaml
> +      - "{{BaseURL}}/jolokia/read<svgxxxxxx>?mimeType=text/html"
@flag007 `<svg onload=alert(document.domain)>` this looks good? if yes I will update the payload.

2020-08-30 13:17 UTC, flag007 commented on cves/CVE-2018-1000129.yaml
> +      - "{{BaseURL}}/jolokia/read<svgxxxxxx>?mimeType=text/html"
You can use <svg onload=alert(document.domain)>

2020-08-30 13:17 UTC, flag007 commented on cves/CVE-2018-1000129.yaml
> +      - "{{BaseURL}}/jolokia/read<svgxxxxxx>?mimeType=text/html"
ok

2020-08-30 13:18 UTC, flag007 commented on cves/CVE-2018-1000129.yaml
> +      - "{{BaseURL}}/jolokia/read<svgxxxxxx>?mimeType=text/html"
this is ok