add CVE-2022-0824
projectdiscovery/nuclei-templates pull request #3845
Opened 2022-03-07 08:01 UTC by cckuailong

### Template / PR Information

Improper Access Control to Remote Code Execution in GitHub repository webmin/webmin prior to 1.990.

- References:
 https://github.com/faisalfs10x/Webmin-CVE-2022-0824-revshell/blob/main/Webmin-revshell.py
 https://nvd.nist.gov/vuln/detail/CVE-2022-0824

### Template Validation

I've validated this template locally?
- YES

Vultarget: 
https://github.com/cckuailong/reapoc/tree/main/2022/CVE-2022-0824/vultarget
<img width="567" alt="1" src="https://user-images.githubusercontent.com/10824150/156991141-8d295cbd-05e1-418b-af3a-67cca2df8f51.png">

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/.github/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

2022-03-19 09:17 UTC, ehsandeep requested changes
thank you for writing this template @cckuailong, Can we consider adding an additional matcher based on page response/status? as some legit/fake servers (unrelated to vulnerable hosts) try to resolve input domain/urls which leads into false-positive results.

I've also created a [separate issue](https://github.com/projectdiscovery/nuclei-templates/issues/3900) for exisitng oast based templates with single matcher.

2022-03-19 10:44 UTC, cckuailong commented
I think dnslog is a stable verify method.

2022-11-08 07:56 UTC, princechaddha approved these changes

2022-11-08 07:57 UTC, princechaddha commented
Hi @cckuailong, The response time to this PR was much longer than usual. Thank you so much for sharing this template with the community and contributing to the project 🍻

2022-11-08 08:00 UTC, merged