Add contributing guidelines
projectdiscovery/nuclei-templates pull request #417
Opened 2020-09-05 07:23 UTC by dwisiswant0

To maintain an ecosystem of nuclei templates, we should have contributing guidelines. Next will be done by @bauthard.

- [x] PR template
- [ ] Contributing guidelines
- [ ] Code of Conduct

2020-09-05 07:48 UTC, bauthard commented
Thank you for proposing this idea, we will work on this.

2021-07-27 17:12 UTC, toufik-airane commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] I have followed the guidelines in our [CONTRIBUTING.md](https://github.com/projectdiscovery/nuclei-templates/blob/master/.github/CONTRIBUTING.md) document.
The link is down. The good one seems to be 
https://github.com/projectdiscovery/nuclei-templates/blob/master/CONTRIBUTING.md.

2021-07-27 17:13 UTC, toufik-airane requested changes
Interesting initiative. 👍 

We should inspire from the [contribution guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/.github/CONTRIBUTING.md).

2021-07-28 00:45 UTC, dwisiswant0 commented
My remote branch is gone. Move to #2236.

2021-07-28 00:45 UTC, closed without merging