Update kubernetes-pods.yaml
projectdiscovery/nuclei-templates pull request #450
Opened 2020-09-13 06:20 UTC by random-robbie

This is a RCE not just information disclosure!

2020-09-13 06:37 UTC, bauthard commented
Hey @random-robbie, 

As this template only includes the detection part, the author marked as `info`, so either we can add some information as a comment to escalate this RCE or have different templates confirming the RCE, what you suggest?

2020-09-16 17:33 UTC, CasperGN commented
I agree with @random-robbie here @bauthard. Regardless of it being a detection and not exploiting, the detection of a RCE is critical.

2020-09-16 17:46 UTC, bauthard commented
Hey @CasperGN, 

I do agree as well, the point is when someone detected this with critical severity, the next question arises, how to achieve the RCE, so either we can add a reference or template for the same to avoid any further confusion.

2020-09-16 17:49 UTC, CasperGN commented
Oh I see, i misunderstood then. 
I guess that goes back to the `desciption:` tag in the templates that didn't really catch on properly?
It would be nice to be able to reference or add further description that the user(s) could query in some way. Fx. links to public PoCs etc.

/ Casper

2020-09-16 18:16 UTC, bauthard commented
Yes, that's the expected information to have @CasperGN, but we don't enforce `desciption` field.

2020-09-17 06:41 UTC, CasperGN requested changes
@random-robbie what if the following:
```yaml
description: When the service port is available, anyone can execute commands inside the container. See https://github.com/officialhocc/Kubernetes-Kubelet-RCE for inspiration.
```
Was added to the `info` section?

2020-09-17 08:53 UTC, merged

2020-09-17 08:53 UTC, bauthard commented
@CasperGN thank you, I've added the extra information.