Update elasticsearch; Add Git, Keycloak, Sercomm RV6699, MOOS and .well-known's
projectdiscovery/nuclei-templates pull request #542
Opened 2020-10-06 22:47 UTC by antonydevanchi

Hi @bauthard. 
Can you review it?

I'll appreciate any feedback.

2020-10-07 19:49 UTC, bauthard commented on files/exposed-git.yaml
> +id: exposed-git
@antonydevanchi we have a template for this at https://github.com/projectdiscovery/nuclei-templates/blob/master/files/git-config.yaml which covers all the cases, do you have any specific example to share where additional endpoints makes difference?

2020-10-07 19:51 UTC, bauthard commented on files/well-known.yaml
> +      - type: status
Checking for `200` status is not a unique identifier, we need to make sure we have a unique identifier for each path/endpoint we are adding here, otherwise, it fails the purpose, many servers will respond with `200` status code for any path you request, in that case, this template will fail.

2020-10-07 19:54 UTC, bauthard commented on proprietary/moos.yaml
> +          - 'relationTypeRefId:personFounder'
we can make use of `condition` as `AND`, the default condition between words matcher is `OR`

```yaml
        words:
          - 'Version'
          - 'busBaseUrl'
          - 'relationTypeRefId:personFounder'
        condition: and
```

2020-10-07 19:55 UTC, bauthard commented on proprietary/moos.yaml
> +          - 'relationTypeRefId:personFounder'
we can also move this to `technology` directory.

2020-10-07 19:56 UTC, bauthard commented on devices/sercomm-rv6699.yaml
> +id: sercomm-rv6699
Can we move this to the technology directory?

2020-10-07 20:00 UTC, bauthard requested changes
@antonydevanchi please review the requested changes, please let us know if you want any help from our side.

2021-02-08 10:32 UTC, ehsandeep commented
Few of the templates are already part of the project, closing this PR due to inactivity and lack of information.

2021-02-08 10:32 UTC, closed without merging