DNS SaaS Service Detection
projectdiscovery/nuclei-templates pull request #6411
Opened 2022-12-21 23:01 UTC by thesubtlety

### Template / PR Information
DNS records often point to SaaS providers that use obscure but static DNS names. Quickly identifying an organization's SaaS providers from DNS records is a useful reconnaissance activity. 

Also conveniently extracts DNS names from A and CNAME records for quick identification of unspecified providers.

Although there are innumerable SaaS providers this PR documents several dozen common ones.

```
[saas-service-detection:Fastly CDN] [dns] [info] blog.projectdiscovery.io [projectdiscovery.ghost.io,ghost.map.fastly.net]
[saas-service-detection:Ghost] [dns] [info] blog.projectdiscovery.io [projectdiscovery.ghost.io,ghost.map.fastly.net]
[saas-service-detection:Cloudflare CDN] [dns] [info] careers.projectdiscovery.io
[saas-service-detection:Cloudflare CDN] [dns] [info] apollo.projectdiscovery.io
[saas-service-detection:Cloudflare CDN] [dns] [info] nexus.projectdiscovery.io
[saas-service-detection:Cloudflare CDN] [dns] [info] stock.walmart.com [webfarm-32.q4web.com,webfarm-30924.q4web.com,webfarm-300.q4web.com,cloudflare.cdn.web.prd.q4inc.com,cloudflare.cdn.web.prd.q4inc.com.cdn.cloudflare.net]
[saas-service-detection:Q4 Investor Relations] [dns] [info] stock.walmart.com [webfarm-32.q4web.com,webfarm-30924.q4web.com,webfarm-[saas-service-detection:Datagrail] [dns] [info] privacy.hashicorp.com [hashicorp.datagrail.io]
[saas-service-detection:Amazon CloudFront] [dns] [info] portal.cloud.hashicorp.com [d2n5045g1kopvr.cloudfront.net]
[saas-service-detection:Heroku] [dns] [info] util.hashicorp.com [util.hashicorp.com.herokudns.com]
[saas-service-detection:Adobe Marketo] [dns] [info] view.hashicorp.com [mkto-ab320182.com]
[saas-service-detection:zendesk] [dns] [info] support.hashicorp.com [hashicorp.ssl.zendesk.com,hashicorp.zendesk.com]
```
### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

2022-12-22 08:47 UTC, ehsandeep commented
Related templates can be removed with this addition.

- https://github.com/projectdiscovery/nuclei-templates/blob/main/dns/cname-fingerprint.yaml
- https://github.com/projectdiscovery/nuclei-templates/blob/main/dns/cname-service.yaml

2022-12-22 08:48 UTC, ehsandeep requested changes

2022-12-22 08:48 UTC, ehsandeep commented on dns/saas-service-detection.yaml
> +        name: WP Engine
@thesubtlety we can replace all the names to lowercase and replace spaces with dash.

- for example, `WP Engine` => `wp-engine`

2022-12-22 16:10 UTC, thesubtlety commented on dns/saas-service-detection.yaml
> +        name: WP Engine
Done. Keep in mind that the cname-fingerprint template detects any CNAME record while this only flags specified records. I suppose this does succeed the cname-service template though (or could be rolled in there).

2023-07-26 16:07 UTC, princechaddha approved these changes

2023-07-27 14:08 UTC, princechaddha approved these changes

2023-07-27 14:11 UTC, merged

2023-07-27 14:12 UTC, princechaddha commented
Hi @thesubtlety, The response time to this PR was much longer than usual. Thank you so much for sharing this template with the community and contributing to this project 🍻

You can join our [discord server](https://discord.com/invite/projectdiscovery). It's a great place to connect with fellow contributors and stay updated with the latest developments. Thank you once again