Create phpmoadmin.yaml
projectdiscovery/nuclei-templates pull request #7012
Opened 2023-03-31 15:54 UTC by Yablargo

### Template / PR Information

Hello Again!

I recently ran across a panel I had never heard of:
![image](https://user-images.githubusercontent.com/4755200/229168801-800663ed-aaa6-4120-9860-c9034274c4c8.png)

I also found that this has a CVE-2015-2208 (and some other nasties that are being disclosed, please don't use this software!)

Included in this PR are the detector, and a forthcoming check for CVE-2015-2208.

- References:
https://www.cvedetails.com/cve/CVE-2015-2208
http://www.phpmoadmin.com/
https://github.com/MongoDB-Rox/phpMoAdmin-MongoDB-Admin-Tool-for-PHP
https://www.exploit-db.com/exploits/36251
### Template Validation

I've validated this template locally?
- [X ] YES
- [ ] NO

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

2023-03-31 16:10 UTC, ehsandeep requested changes
@Yablargo we can add `matchers-condition: and` to ensure both conditions are matched.

2023-03-31 16:49 UTC, Yablargo commented
I was using the following docker compose def when testing and on entrypoint of the moadmin changing the connection string:

```yaml
# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:3.6.20
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example    
    ports:
      - 27017:27017
    volumes:
      - ./mongodata:/data/db
    expose: 
      - 27017
  
  admin:
    image: thinkcube/phpmoadmin:latest
    ports:
      - 80:80
    expose: 
      - 80
    entrypoint: ["sh", "/app/docker-entrypoint.sh"]
    
```

2023-04-06 03:30 UTC, pussycat0x commented
Hi @Yablargo  i tried to setup the docker env and it's not working. can you share a debug data for this template? 💯

2024-01-19 19:13 UTC, ehsandeep commented
Apologies for the delayed response, closing this PR as we are unable to verify the template due to insuffient information to verify this vulnerability.

2024-01-19 19:13 UTC, closed without merging

2024-01-21 21:39 UTC, S4lt5 commented
That's fair, this really slipped off my radar with other bit things going on. While the maintainer apparently slipped bugs back in unannaounced, the user base of this is pretty low.

Anyone using this should probably assume its being maliciously updated at this point, but I don't think the prevalence is really that high.