resin information disclosure
projectdiscovery/nuclei-templates pull request #793
Opened 2021-02-01 15:49 UTC by pikpikcu

```
                       __     _ 
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ / 
   / / / / /_/ / /__/ /  __/ /  
  /_/ /_/\__,_/\___/_/\___/_/   v2.1									  

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] [Caucho-Resin-Information-Disclosure] Loaded template Caucho Resin Information Disclosure (@pikpikcu) [info]
[Caucho-Resin-Information-Disclosure] [http] https://REDACTED/resin-doc/viewfile/?file=/WEB-INF/resin-web.xml
[Caucho-Resin-Information-Disclosure] [http] https://REDACTED/%20../web-inf/web.xml
[Caucho-Resin-Information-Disclosure] [http] https://REDACTED/resin-doc/viewfile/?file=/WEB-INF/resin-web.xml
[Caucho-Resin-Information-Disclosure] [http] https://REDACTED/resin-doc/viewfile/?file=/WEB-INF/resin-web.xml

```

2021-07-27 18:00 UTC, toufik-airane requested changes
Dear @pikpikcu,

Thank you for your contribution.

After discussion, we've figured out that the open and close tag could be more appropriate to avoid false positives.

What do you think about the proposed changes?

Thank you.

2021-07-27 18:00 UTC, toufik-airane commented on vulnerabilities/other/caucho-resin-info-disclosure.yaml
> +        part: body
```suggestion
    matchers:
      - type: word
        words:
          - "<web-app"
          - "</web-app>"
        part: body
        condition: and
```

2021-08-19 16:46 UTC, toufik-airane commented
Dear @pikpikcu,

Just a little reminder. :)
I think we can agree that the use of the new wording could decrease false positives.

Thank you for your answer.

2021-08-19 16:47 UTC, toufik-airane commented
Dear @ehsandeep,

Do you think we can merge this one with the changes?

Thanks.

2021-08-19 17:45 UTC, ehsandeep approved these changes

2021-08-19 17:45 UTC, ehsandeep commented
made some changes, looks good to me @toufik-airane.

2021-08-19 17:45 UTC, merged